name: Main

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip install .[test]
        git clone --depth 1 https://github.com/pyvec/pyvo-data pyvocz/pyvo-data
    - name: Run tests
      run: |
        python -m pytest -vv test_pyvocz
